apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/l0s3rc0d3/argocd-sync
    targetRevision: HEAD
    path: charts/nginx-app
    helm:
      releaseName: nginx-app-dev
      valueFiles:
        - overrides/override.dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true